/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.BookingManagementController;

/**
 *
 * @author alex
 */
public class BookingManagement extends javax.swing.JFrame {

    /**
     * Creates new form BookingManagement
     */
    public BookingManagement() {
        initComponents();
        new BookingManagementController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookingManagementPanel = new javax.swing.JPanel();
        hotelManagementMenu = new javax.swing.JLabel();
        chooseOptionPrompt = new javax.swing.JLabel();
        bookNewRoom = new javax.swing.JButton();
        cancelBooking = new javax.swing.JButton();
        extendBooking = new javax.swing.JButton();
        previousMenu = new javax.swing.JButton();
        changeRoom = new javax.swing.JButton();
        viewGuestBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bookingManagementPanel.setBackground(new java.awt.Color(255, 255, 255));

        hotelManagementMenu.setBackground(new java.awt.Color(255, 255, 255));
        hotelManagementMenu.setFont(new java.awt.Font("STSong", 1, 40)); // NOI18N
        hotelManagementMenu.setForeground(new java.awt.Color(0, 0, 0));
        hotelManagementMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelManagementMenu.setText("Booking Management Menu");
        hotelManagementMenu.setPreferredSize(new java.awt.Dimension(220, 50));

        chooseOptionPrompt.setBackground(new java.awt.Color(255, 255, 255));
        chooseOptionPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        chooseOptionPrompt.setForeground(new java.awt.Color(0, 0, 0));
        chooseOptionPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseOptionPrompt.setText("Choose your option");

        bookNewRoom.setBackground(new java.awt.Color(255, 204, 255));
        bookNewRoom.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        bookNewRoom.setForeground(new java.awt.Color(0, 0, 0));
        bookNewRoom.setText("Book room");

        cancelBooking.setBackground(new java.awt.Color(255, 204, 255));
        cancelBooking.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        cancelBooking.setForeground(new java.awt.Color(0, 0, 0));
        cancelBooking.setText("Cancel booking");

        extendBooking.setBackground(new java.awt.Color(255, 204, 255));
        extendBooking.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        extendBooking.setForeground(new java.awt.Color(0, 0, 0));
        extendBooking.setText("Extend booking");

        previousMenu.setBackground(new java.awt.Color(153, 0, 153));
        previousMenu.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        previousMenu.setForeground(new java.awt.Color(255, 255, 255));
        previousMenu.setText("Return to Previous Menu");

        changeRoom.setBackground(new java.awt.Color(255, 204, 255));
        changeRoom.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        changeRoom.setForeground(new java.awt.Color(0, 0, 0));
        changeRoom.setText("Change room");

        viewGuestBooking.setBackground(new java.awt.Color(255, 204, 255));
        viewGuestBooking.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        viewGuestBooking.setForeground(new java.awt.Color(0, 0, 0));
        viewGuestBooking.setText("View guest booking");

        javax.swing.GroupLayout bookingManagementPanelLayout = new javax.swing.GroupLayout(bookingManagementPanel);
        bookingManagementPanel.setLayout(bookingManagementPanelLayout);
        bookingManagementPanelLayout.setHorizontalGroup(
            bookingManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingManagementPanelLayout.createSequentialGroup()
                .addGroup(bookingManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingManagementPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(bookingManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookNewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extendBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previousMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewGuestBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bookingManagementPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(hotelManagementMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookingManagementPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(chooseOptionPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        bookingManagementPanelLayout.setVerticalGroup(
            bookingManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingManagementPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(hotelManagementMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(chooseOptionPrompt)
                .addGap(44, 44, 44)
                .addComponent(bookNewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(extendBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewGuestBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(previousMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(bookingManagementPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public javax.swing.JButton getBookNewRoomButton() {
        return bookNewRoom;
    }

    public javax.swing.JButton getCancelBookingButton() {
        return cancelBooking;
    }

    public javax.swing.JButton getChangeRoomButton() {
        return changeRoom;
    }

    public javax.swing.JButton getExtendBookingButton() {
        return extendBooking;
    }

    public javax.swing.JButton getPreviousMenuButton() {
        return previousMenu;
    }

    public javax.swing.JButton getViewGuestBookingButton() {
        return viewGuestBooking;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookNewRoom;
    private javax.swing.JPanel bookingManagementPanel;
    private javax.swing.JButton cancelBooking;
    private javax.swing.JButton changeRoom;
    private javax.swing.JLabel chooseOptionPrompt;
    private javax.swing.JButton extendBooking;
    private javax.swing.JLabel hotelManagementMenu;
    private javax.swing.JButton previousMenu;
    private javax.swing.JButton viewGuestBooking;
    // End of variables declaration//GEN-END:variables


    
}
