/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class BookRoom extends javax.swing.JFrame {

    /**
     * Creates new form BookRoom
     */
    public BookRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookRoomPanel = new javax.swing.JPanel();
        bookingRoom = new javax.swing.JLabel();
        chooseEnterPrompt = new javax.swing.JLabel();
        checkInDate = new javax.swing.JTextField();
        checkOutDate = new javax.swing.JTextField();
        confirmBooking = new javax.swing.JButton();
        hotelChoice = new javax.swing.JComboBox<>();
        availableRoomsPrompt = new javax.swing.JLabel();
        chooseHotel = new javax.swing.JLabel();
        avaiableRoomsQTY = new javax.swing.JLabel();
        numberOfRooms = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bookRoomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bookRoomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bookingRoom.setBackground(new java.awt.Color(255, 255, 255));
        bookingRoom.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        bookingRoom.setForeground(new java.awt.Color(0, 0, 0));
        bookingRoom.setText("Booking Room");
        bookingRoom.setPreferredSize(new java.awt.Dimension(220, 50));

        chooseEnterPrompt.setBackground(new java.awt.Color(255, 255, 255));
        chooseEnterPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        chooseEnterPrompt.setForeground(new java.awt.Color(0, 0, 0));
        chooseEnterPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseEnterPrompt.setText("Choose & Enter");

        checkInDate.setBackground(new java.awt.Color(255, 204, 255));
        checkInDate.setForeground(new java.awt.Color(102, 102, 102));
        checkInDate.setText("Check-in date (yyyy-mm-dd)");
        checkInDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInDateActionPerformed(evt);
            }
        });

        checkOutDate.setBackground(new java.awt.Color(255, 204, 255));
        checkOutDate.setForeground(new java.awt.Color(102, 102, 102));
        checkOutDate.setText("Check-out date (yyyy-mm-dd)");

        confirmBooking.setBackground(new java.awt.Color(153, 0, 153));
        confirmBooking.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        confirmBooking.setForeground(new java.awt.Color(255, 255, 255));
        confirmBooking.setText("Confirm Booking");
        confirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingActionPerformed(evt);
            }
        });

        hotelChoice.setBackground(new java.awt.Color(255, 204, 255));
        hotelChoice.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        hotelChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auckland Skyline", "Queenstown Grand" }));

        availableRoomsPrompt.setBackground(new java.awt.Color(255, 255, 255));
        availableRoomsPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        availableRoomsPrompt.setForeground(new java.awt.Color(0, 0, 0));
        availableRoomsPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        availableRoomsPrompt.setText("Available Rooms");

        chooseHotel.setBackground(new java.awt.Color(255, 255, 255));
        chooseHotel.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        chooseHotel.setForeground(new java.awt.Color(0, 0, 0));
        chooseHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseHotel.setText("Choose Hotel");

        avaiableRoomsQTY.setBackground(new java.awt.Color(255, 255, 255));
        avaiableRoomsQTY.setFont(new java.awt.Font("STSong", 1, 30)); // NOI18N
        avaiableRoomsQTY.setForeground(new java.awt.Color(153, 0, 153));
        avaiableRoomsQTY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avaiableRoomsQTY.setText("?");
        avaiableRoomsQTY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        numberOfRooms.setBackground(new java.awt.Color(255, 204, 255));
        numberOfRooms.setForeground(new java.awt.Color(102, 102, 102));
        numberOfRooms.setText("Enter number of the rooms you want to book");

        javax.swing.GroupLayout bookRoomPanelLayout = new javax.swing.GroupLayout(bookRoomPanel);
        bookRoomPanel.setLayout(bookRoomPanelLayout);
        bookRoomPanelLayout.setHorizontalGroup(
            bookRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookRoomPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(bookRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookRoomPanelLayout.createSequentialGroup()
                        .addComponent(bookingRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookRoomPanelLayout.createSequentialGroup()
                        .addGroup(bookRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bookRoomPanelLayout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addGroup(bookRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(bookRoomPanelLayout.createSequentialGroup()
                                        .addComponent(availableRoomsPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(avaiableRoomsQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49))
                                    .addComponent(checkInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberOfRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bookRoomPanelLayout.createSequentialGroup()
                                .addComponent(chooseHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bookRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chooseEnterPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hotelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48))))
        );
        bookRoomPanelLayout.setVerticalGroup(
            bookRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookRoomPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(bookingRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(chooseEnterPrompt)
                .addGap(18, 18, 18)
                .addGroup(bookRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numberOfRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bookRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avaiableRoomsQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableRoomsPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(bookRoomPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInDateActionPerformed

    private void confirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avaiableRoomsQTY;
    private javax.swing.JLabel availableRoomsPrompt;
    private javax.swing.JPanel bookRoomPanel;
    private javax.swing.JLabel bookingRoom;
    private javax.swing.JTextField checkInDate;
    private javax.swing.JTextField checkOutDate;
    private javax.swing.JLabel chooseEnterPrompt;
    private javax.swing.JLabel chooseHotel;
    private javax.swing.JButton confirmBooking;
    private javax.swing.JComboBox<String> hotelChoice;
    private javax.swing.JTextField numberOfRooms;
    // End of variables declaration//GEN-END:variables
}
