/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class CancelBookingStaff extends javax.swing.JFrame {

    /**
     * Creates new form CancelBooking
     */
    public CancelBookingStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelBookingStaffPanel = new javax.swing.JPanel();
        guestUsername = new javax.swing.JTextField();
        bookingID = new javax.swing.JTextField();
        confirmCancel = new javax.swing.JButton();
        cancelBooking = new javax.swing.JLabel();
        bookingDetailsPrompt = new javax.swing.JLabel();
        returnPreviousMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cancelBookingStaffPanel.setBackground(new java.awt.Color(255, 255, 255));

        guestUsername.setBackground(new java.awt.Color(255, 204, 255));
        guestUsername.setForeground(new java.awt.Color(102, 102, 102));
        guestUsername.setText("Enter guest username");
        guestUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestUsernameActionPerformed(evt);
            }
        });

        bookingID.setBackground(new java.awt.Color(255, 204, 255));
        bookingID.setForeground(new java.awt.Color(102, 102, 102));
        bookingID.setText("Enter booking ID you want to cancel");

        confirmCancel.setBackground(new java.awt.Color(153, 0, 153));
        confirmCancel.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        confirmCancel.setForeground(new java.awt.Color(255, 255, 255));
        confirmCancel.setText("Confirm");
        confirmCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmCancelActionPerformed(evt);
            }
        });

        cancelBooking.setBackground(new java.awt.Color(255, 255, 255));
        cancelBooking.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        cancelBooking.setForeground(new java.awt.Color(0, 0, 0));
        cancelBooking.setText("Cancel Booking");
        cancelBooking.setPreferredSize(new java.awt.Dimension(220, 50));

        bookingDetailsPrompt.setBackground(new java.awt.Color(255, 255, 255));
        bookingDetailsPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        bookingDetailsPrompt.setForeground(new java.awt.Color(0, 0, 0));
        bookingDetailsPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingDetailsPrompt.setText("Enter booking details");

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");

        javax.swing.GroupLayout cancelBookingStaffPanelLayout = new javax.swing.GroupLayout(cancelBookingStaffPanel);
        cancelBookingStaffPanel.setLayout(cancelBookingStaffPanelLayout);
        cancelBookingStaffPanelLayout.setHorizontalGroup(
            cancelBookingStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBookingStaffPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(bookingDetailsPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingStaffPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(cancelBookingStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingStaffPanelLayout.createSequentialGroup()
                        .addGroup(cancelBookingStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guestUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingStaffPanelLayout.createSequentialGroup()
                        .addComponent(cancelBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingStaffPanelLayout.createSequentialGroup()
                        .addComponent(returnPreviousMenu)
                        .addGap(205, 205, 205))))
        );
        cancelBookingStaffPanelLayout.setVerticalGroup(
            cancelBookingStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBookingStaffPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(cancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(bookingDetailsPrompt)
                .addGap(55, 55, 55)
                .addComponent(guestUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnPreviousMenu)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(cancelBookingStaffPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guestUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestUsernameActionPerformed

    private void confirmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelBookingStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelBookingStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelBookingStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelBookingStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelBookingStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingDetailsPrompt;
    private javax.swing.JTextField bookingID;
    private javax.swing.JLabel cancelBooking;
    private javax.swing.JPanel cancelBookingStaffPanel;
    private javax.swing.JButton confirmCancel;
    private javax.swing.JTextField guestUsername;
    private javax.swing.JButton returnPreviousMenu;
    // End of variables declaration//GEN-END:variables
}
