/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ChangeRoomStaffController;

/**
 *
 * @author alex
 */
public class ChangeRoomStaff extends javax.swing.JFrame {

    /**
     * Creates new form ChangeRoom
     */
    public ChangeRoomStaff() {
        initComponents();
        new ChangeRoomStaffController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        changeRoomPanel = new javax.swing.JPanel();
        changeRoom = new javax.swing.JLabel();
        enterGuestUsername = new javax.swing.JTextField();
        enterBookingID = new javax.swing.JTextField();
        checkAvailabilityRoom = new javax.swing.JButton();
        returnPreviousMenu = new javax.swing.JButton();
        bookingScrollArea = new javax.swing.JScrollPane();
        bookingTextArea = new javax.swing.JTextArea();
        search = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        changeRoomPanel.setBackground(new java.awt.Color(255, 255, 255));

        changeRoom.setBackground(new java.awt.Color(255, 255, 255));
        changeRoom.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        changeRoom.setForeground(new java.awt.Color(0, 0, 0));
        changeRoom.setText("Change Room");
        changeRoom.setPreferredSize(new java.awt.Dimension(220, 50));

        enterGuestUsername.setBackground(new java.awt.Color(255, 204, 255));
        enterGuestUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        enterGuestUsername.setForeground(new java.awt.Color(102, 102, 102));
        enterGuestUsername.setText("Enter guest username");

        enterBookingID.setBackground(new java.awt.Color(255, 204, 255));
        enterBookingID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        enterBookingID.setForeground(new java.awt.Color(102, 102, 102));
        enterBookingID.setText("Enter your booking ID");

        checkAvailabilityRoom.setBackground(new java.awt.Color(153, 0, 153));
        checkAvailabilityRoom.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        checkAvailabilityRoom.setForeground(new java.awt.Color(255, 255, 255));
        checkAvailabilityRoom.setText("Check Available Room");

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");

        bookingTextArea.setColumns(20);
        bookingTextArea.setRows(5);
        bookingTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Bookings", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Helvetica Neue", 1, 13), new java.awt.Color(153, 0, 153))); // NOI18N
        bookingScrollArea.setViewportView(bookingTextArea);

        search.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        search.setForeground(new java.awt.Color(153, 0, 153));
        search.setText("Search");

        javax.swing.GroupLayout changeRoomPanelLayout = new javax.swing.GroupLayout(changeRoomPanel);
        changeRoomPanel.setLayout(changeRoomPanelLayout);
        changeRoomPanelLayout.setHorizontalGroup(
            changeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeRoomPanelLayout.createSequentialGroup()
                .addGroup(changeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeRoomPanelLayout.createSequentialGroup()
                        .addGroup(changeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(changeRoomPanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(changeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkAvailabilityRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterBookingID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(changeRoomPanelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(changeRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(changeRoomPanelLayout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(returnPreviousMenu))
                            .addGroup(changeRoomPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(enterGuestUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(changeRoomPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookingScrollArea)))
                .addContainerGap())
        );
        changeRoomPanelLayout.setVerticalGroup(
            changeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeRoomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(enterGuestUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingScrollArea, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkAvailabilityRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnPreviousMenu)
                .addContainerGap())
        );

        getContentPane().add(changeRoomPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bookingScrollArea;
    private javax.swing.JTextArea bookingTextArea;
    private javax.swing.JLabel changeRoom;
    private javax.swing.JPanel changeRoomPanel;
    private javax.swing.JButton checkAvailabilityRoom;
    private javax.swing.JTextField enterBookingID;
    private javax.swing.JTextField enterGuestUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton returnPreviousMenu;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextArea getBookingTextArea() {
        return bookingTextArea;
    }

    public javax.swing.JTextField getEnterBookingID() {
        return enterBookingID;
    }

    public javax.swing.JTextField getEnterGuestUsername() {
        return enterGuestUsername;
    }

    public javax.swing.JButton getReturnPreviousMenu() {
        return returnPreviousMenu;
    }

    public javax.swing.JButton getSearch() {
        return search;
    }
    
    public javax.swing.JButton getCheckAvailabilityRoom(){
        return checkAvailabilityRoom;
    }
}
