/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ChangeRoomGuestController;

/**
 *
 * @author alex
 */
public class ChangeRoomGuest extends javax.swing.JFrame {

    /**
     * Creates new form ChangeRoomGuest
     */
    public ChangeRoomGuest() {
        initComponents();
        new ChangeRoomGuestController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeRoomGuestPanel = new javax.swing.JPanel();
        enterBookingID = new javax.swing.JTextField();
        changeRoom = new javax.swing.JLabel();
        checkRoomAvailability = new javax.swing.JButton();
        returnPreviousMenu = new javax.swing.JButton();
        bookingScrollArea = new javax.swing.JScrollPane();
        bookingTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        changeRoomGuestPanel.setBackground(new java.awt.Color(255, 255, 255));

        enterBookingID.setBackground(new java.awt.Color(255, 204, 255));
        enterBookingID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        enterBookingID.setForeground(new java.awt.Color(102, 102, 102));
        enterBookingID.setText("Enter your booking ID to change room");

        changeRoom.setBackground(new java.awt.Color(255, 255, 255));
        changeRoom.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        changeRoom.setForeground(new java.awt.Color(0, 0, 0));
        changeRoom.setText("Change Room");
        changeRoom.setPreferredSize(new java.awt.Dimension(220, 50));

        checkRoomAvailability.setBackground(new java.awt.Color(153, 0, 153));
        checkRoomAvailability.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        checkRoomAvailability.setForeground(new java.awt.Color(255, 255, 255));
        checkRoomAvailability.setText("Check Available Room");

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");

        bookingTextArea.setColumns(20);
        bookingTextArea.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        bookingTextArea.setRows(5);
        bookingTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Bookings", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Helvetica Neue", 1, 13), new java.awt.Color(153, 0, 153))); // NOI18N
        bookingScrollArea.setViewportView(bookingTextArea);

        javax.swing.GroupLayout changeRoomGuestPanelLayout = new javax.swing.GroupLayout(changeRoomGuestPanel);
        changeRoomGuestPanel.setLayout(changeRoomGuestPanelLayout);
        changeRoomGuestPanelLayout.setHorizontalGroup(
            changeRoomGuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeRoomGuestPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(changeRoomGuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkRoomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeRoomGuestPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnPreviousMenu)
                .addGap(205, 205, 205))
            .addGroup(changeRoomGuestPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(changeRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(changeRoomGuestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingScrollArea)
                .addContainerGap())
        );
        changeRoomGuestPanelLayout.setVerticalGroup(
            changeRoomGuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeRoomGuestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingScrollArea, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRoomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnPreviousMenu)
                .addContainerGap())
        );

        getContentPane().add(changeRoomGuestPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bookingScrollArea;
    private javax.swing.JTextArea bookingTextArea;
    private javax.swing.JLabel changeRoom;
    private javax.swing.JPanel changeRoomGuestPanel;
    private javax.swing.JButton checkRoomAvailability;
    private javax.swing.JTextField enterBookingID;
    private javax.swing.JButton returnPreviousMenu;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextArea getBookingTextArea() {
        return bookingTextArea;
    }

    public javax.swing.JButton getCheckRoomAvailability() {
        return checkRoomAvailability;
    }

    public javax.swing.JTextField getEnterBookingID() {
        return enterBookingID;
    }

    public javax.swing.JButton getReturnPreviousMenu() {
        return returnPreviousMenu;
    }
}
