/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DisplayInvoiceController;

/**
 *
 * @author alex
 */
public class DisplayInvoice extends javax.swing.JFrame {

    /**
     * Creates new form DisplayInvoice
     */
    public DisplayInvoice() {
        initComponents();
        new DisplayInvoiceController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayInvoicePanel = new javax.swing.JPanel();
        invoice = new javax.swing.JLabel();
        scrollInvoicePanel = new javax.swing.JScrollPane();
        invoiceDisplayArea = new javax.swing.JTextArea();
        returnPreviousMenu = new javax.swing.JButton();
        enterBookingID = new javax.swing.JTextField();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        displayInvoicePanel.setBackground(new java.awt.Color(255, 204, 255));

        invoice.setBackground(new java.awt.Color(255, 204, 255));
        invoice.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        invoice.setForeground(new java.awt.Color(0, 0, 0));
        invoice.setText("Invoice");
        invoice.setPreferredSize(new java.awt.Dimension(220, 50));

        invoiceDisplayArea.setColumns(20);
        invoiceDisplayArea.setFont(new java.awt.Font("STSong", 0, 13)); // NOI18N
        invoiceDisplayArea.setRows(5);
        invoiceDisplayArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice Print", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Helvetica Neue", 1, 13), new java.awt.Color(153, 0, 153))); // NOI18N
        scrollInvoicePanel.setViewportView(invoiceDisplayArea);

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");

        enterBookingID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        enterBookingID.setForeground(new java.awt.Color(102, 102, 102));
        enterBookingID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterBookingID.setText("Enter booking ID to view invoice");
        enterBookingID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBookingIDActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        search.setForeground(new java.awt.Color(153, 0, 153));
        search.setText("Search");

        javax.swing.GroupLayout displayInvoicePanelLayout = new javax.swing.GroupLayout(displayInvoicePanel);
        displayInvoicePanel.setLayout(displayInvoicePanelLayout);
        displayInvoicePanelLayout.setHorizontalGroup(
            displayInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayInvoicePanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayInvoicePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(returnPreviousMenu)
                .addGap(207, 207, 207))
            .addComponent(scrollInvoicePanel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayInvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterBookingID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        displayInvoicePanelLayout.setVerticalGroup(
            displayInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayInvoicePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(enterBookingID))
                .addGap(8, 8, 8)
                .addComponent(scrollInvoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnPreviousMenu)
                .addContainerGap())
        );

        getContentPane().add(displayInvoicePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterBookingIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBookingIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterBookingIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayInvoice().setVisible(true);
            }
        });
    }
    
    public javax.swing.JTextArea getInvoiceTextArea(){
        return invoiceDisplayArea;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayInvoicePanel;
    private javax.swing.JTextField enterBookingID;
    private javax.swing.JLabel invoice;
    private javax.swing.JTextArea invoiceDisplayArea;
    private javax.swing.JButton returnPreviousMenu;
    private javax.swing.JScrollPane scrollInvoicePanel;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
