/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DisplayInvoiceController;

/**
 *
 * @author alex
 */
public class DisplayInvoice extends javax.swing.JFrame {

    /**
     * Creates new form DisplayInvoice
     */
    public DisplayInvoice() {
        initComponents();
        new DisplayInvoiceController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayInvoicePanel = new javax.swing.JPanel();
        invoice = new javax.swing.JLabel();
        scrollInvoicePanel = new javax.swing.JScrollPane();
<<<<<<< HEAD
        invoiceDisplayArea = new javax.swing.JTextArea();
        returnPreviousMenu = new javax.swing.JButton();
=======
        invoiceTextArea = new javax.swing.JTextArea();
>>>>>>> e9150b2 (Implement Add Hotel)

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        displayInvoicePanel.setBackground(new java.awt.Color(255, 204, 255));

        invoice.setBackground(new java.awt.Color(255, 204, 255));
        invoice.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        invoice.setForeground(new java.awt.Color(0, 0, 0));
        invoice.setText("Invoice");
        invoice.setPreferredSize(new java.awt.Dimension(220, 50));

<<<<<<< HEAD
        invoiceDisplayArea.setColumns(20);
        invoiceDisplayArea.setFont(new java.awt.Font("STSong", 0, 13)); // NOI18N
        invoiceDisplayArea.setRows(5);
        invoiceDisplayArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scrollInvoicePanel.setViewportView(invoiceDisplayArea);

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");
=======
        invoiceTextArea.setColumns(20);
        invoiceTextArea.setFont(new java.awt.Font("STSong", 0, 13)); // NOI18N
        invoiceTextArea.setRows(5);
        scrollInvoicePanel.setViewportView(invoiceTextArea);
>>>>>>> e9150b2 (Implement Add Hotel)

        javax.swing.GroupLayout displayInvoicePanelLayout = new javax.swing.GroupLayout(displayInvoicePanel);
        displayInvoicePanel.setLayout(displayInvoicePanelLayout);
        displayInvoicePanelLayout.setHorizontalGroup(
            displayInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayInvoicePanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayInvoicePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(returnPreviousMenu)
                .addGap(207, 207, 207))
            .addComponent(scrollInvoicePanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        displayInvoicePanelLayout.setVerticalGroup(
            displayInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayInvoicePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollInvoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnPreviousMenu)
                .addContainerGap())
        );

        getContentPane().add(displayInvoicePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayInvoice().setVisible(true);
            }
        });
    }
    
    public javax.swing.JTextArea getInvoiceTextArea(){
        return invoiceTextArea;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayInvoicePanel;
<<<<<<< HEAD
    private javax.swing.JLabel invoice;
    private javax.swing.JTextArea invoiceDisplayArea;
    private javax.swing.JButton returnPreviousMenu;
=======
    private javax.swing.JTextArea invoiceTextArea;
>>>>>>> e9150b2 (Implement Add Hotel)
    private javax.swing.JScrollPane scrollInvoicePanel;
    // End of variables declaration//GEN-END:variables
}
