/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class HotelDetails extends javax.swing.JFrame {

    /**
     * Creates new form HotelDetails
     */
    public HotelDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotelDetailsPanel = new javax.swing.JPanel();
        hotelDetails = new javax.swing.JLabel();
        enterHotelDetailsPrompt = new javax.swing.JLabel();
        hotelID = new javax.swing.JTextField();
        newHotelName = new javax.swing.JTextField();
        hotelLocation = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        returnPreviousMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        hotelDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        hotelDetails.setBackground(new java.awt.Color(255, 255, 255));
        hotelDetails.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        hotelDetails.setForeground(new java.awt.Color(0, 0, 0));
        hotelDetails.setText("Hotel Details");
        hotelDetails.setPreferredSize(new java.awt.Dimension(220, 50));

        enterHotelDetailsPrompt.setBackground(new java.awt.Color(255, 255, 255));
        enterHotelDetailsPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        enterHotelDetailsPrompt.setForeground(new java.awt.Color(0, 0, 0));
        enterHotelDetailsPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterHotelDetailsPrompt.setText("Enter Hotel Details");

        hotelID.setBackground(new java.awt.Color(255, 204, 255));
        hotelID.setForeground(new java.awt.Color(102, 102, 102));
        hotelID.setText("Enter hotel ID to update");

        newHotelName.setBackground(new java.awt.Color(255, 204, 255));
        newHotelName.setForeground(new java.awt.Color(102, 102, 102));
        newHotelName.setText("Enter new hotel name");

        hotelLocation.setBackground(new java.awt.Color(255, 204, 255));
        hotelLocation.setForeground(new java.awt.Color(102, 102, 102));
        hotelLocation.setText("Enter new location");

        confirm.setBackground(new java.awt.Color(153, 0, 153));
        confirm.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirm");

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");

        javax.swing.GroupLayout hotelDetailsPanelLayout = new javax.swing.GroupLayout(hotelDetailsPanel);
        hotelDetailsPanel.setLayout(hotelDetailsPanelLayout);
        hotelDetailsPanelLayout.setHorizontalGroup(
            hotelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelDetailsPanelLayout.createSequentialGroup()
                .addGroup(hotelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelDetailsPanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(enterHotelDetailsPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hotelDetailsPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(hotelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hotelDetailsPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(hotelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(hotelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hotelDetailsPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(returnPreviousMenu)))

                            
                .addContainerGap(51, Short.MAX_VALUE))
        );
        hotelDetailsPanelLayout.setVerticalGroup(
            hotelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelDetailsPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(hotelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterHotelDetailsPrompt)
                .addGap(43, 43, 43)
                .addComponent(hotelID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hotelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnPreviousMenu)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        getContentPane().add(hotelDetailsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JLabel enterHotelDetailsPrompt;
    private javax.swing.JLabel hotelDetails;
    private javax.swing.JPanel hotelDetailsPanel;
    private javax.swing.JTextField hotelID;
    private javax.swing.JTextField hotelLocation;
    private javax.swing.JTextField newHotelName;
    private javax.swing.JButton returnPreviousMenu;
    // End of variables declaration//GEN-END:variables

   
    public javax.swing.JButton getConfirm() {
        return confirm;
    }

    public javax.swing.JTextField getHotelID() {
        return hotelID;
    }

    public javax.swing.JTextField getHotelLocation() {
        return hotelLocation;
    }

    public javax.swing.JTextField getNewHotelName() {
        return newHotelName;
    }
}
