/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.RemoveRoomController;

/**
 *
 * @author alex
 */
public class RemoveRoom extends javax.swing.JFrame {

    /**
     * Creates new form RemoveRoom
     */
    public RemoveRoom() {
        initComponents();
        new RemoveRoomController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeRoomPanel = new javax.swing.JPanel();
        hotelID = new javax.swing.JTextField();
        roomID = new javax.swing.JTextField();
        confirmRemove = new javax.swing.JButton();
        removeRoom = new javax.swing.JLabel();
        createNewHotelPrompt = new javax.swing.JLabel();
        returnPreviousMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        removeRoomPanel.setBackground(new java.awt.Color(255, 255, 255));

        hotelID.setBackground(new java.awt.Color(255, 204, 255));
        hotelID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        hotelID.setForeground(new java.awt.Color(102, 102, 102));
        hotelID.setText("Enter Hotel ID");

        roomID.setBackground(new java.awt.Color(255, 204, 255));
        roomID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        roomID.setForeground(new java.awt.Color(102, 102, 102));
        roomID.setText("Enter Room ID to Remove");

        confirmRemove.setBackground(new java.awt.Color(153, 0, 153));
        confirmRemove.setFont(new java.awt.Font("STSong", 1, 28)); // NOI18N
        confirmRemove.setForeground(new java.awt.Color(255, 255, 255));
        confirmRemove.setText("Confirm");

        removeRoom.setBackground(new java.awt.Color(255, 255, 255));
        removeRoom.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        removeRoom.setForeground(new java.awt.Color(0, 0, 0));
        removeRoom.setText("Remove Room");
        removeRoom.setPreferredSize(new java.awt.Dimension(220, 50));

        createNewHotelPrompt.setBackground(new java.awt.Color(255, 255, 255));
        createNewHotelPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        createNewHotelPrompt.setForeground(new java.awt.Color(0, 0, 0));
        createNewHotelPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createNewHotelPrompt.setText("Enter room details");

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");

        javax.swing.GroupLayout removeRoomPanelLayout = new javax.swing.GroupLayout(removeRoomPanel);
        removeRoomPanel.setLayout(removeRoomPanelLayout);
        removeRoomPanelLayout.setHorizontalGroup(
            removeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeRoomPanelLayout.createSequentialGroup()
                .addGroup(removeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeRoomPanelLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(createNewHotelPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeRoomPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(removeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotelID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(removeRoomPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(removeRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeRoomPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(returnPreviousMenu)
                .addGap(207, 207, 207))
        );
        removeRoomPanelLayout.setVerticalGroup(
            removeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeRoomPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(removeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(createNewHotelPrompt)
                .addGap(45, 45, 45)
                .addComponent(hotelID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnPreviousMenu)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(removeRoomPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmRemove;
    private javax.swing.JLabel createNewHotelPrompt;
    private javax.swing.JTextField hotelID;
    private javax.swing.JLabel removeRoom;
    private javax.swing.JPanel removeRoomPanel;
    private javax.swing.JButton returnPreviousMenu;
    private javax.swing.JTextField roomID;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getConfirmRemove() {
        return confirmRemove;
    }

    public javax.swing.JTextField getHotelID() {
        return hotelID;
    }

    public javax.swing.JButton getReturnPreviousMenu() {
        return returnPreviousMenu;
    }

    public javax.swing.JTextField getRoomID() {
        return roomID;
    }
}
