/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class RoomDetails extends javax.swing.JFrame {

    /**
     * Creates new form RoomDetails
     */
    public RoomDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomDetailsPanel = new javax.swing.JPanel();
        roomDetails = new javax.swing.JLabel();
        roomDetailsPrompt = new javax.swing.JLabel();
        hotelID = new javax.swing.JTextField();
        roomID = new javax.swing.JTextField();
        roomType = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        roomPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        roomDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        roomDetails.setBackground(new java.awt.Color(255, 255, 255));
        roomDetails.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        roomDetails.setForeground(new java.awt.Color(0, 0, 0));
        roomDetails.setText("Room Details");
        roomDetails.setPreferredSize(new java.awt.Dimension(220, 50));

        roomDetailsPrompt.setBackground(new java.awt.Color(255, 255, 255));
        roomDetailsPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        roomDetailsPrompt.setForeground(new java.awt.Color(0, 0, 0));
        roomDetailsPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomDetailsPrompt.setText("Enter Room Details");

        hotelID.setBackground(new java.awt.Color(255, 204, 255));
        hotelID.setForeground(new java.awt.Color(102, 102, 102));
        hotelID.setText("Enter hotel ID");
        hotelID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelIDActionPerformed(evt);
            }
        });

        roomID.setBackground(new java.awt.Color(255, 204, 255));
        roomID.setForeground(new java.awt.Color(102, 102, 102));
        roomID.setText("Enter room ID to update");
        roomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomIDActionPerformed(evt);
            }
        });

        roomType.setBackground(new java.awt.Color(255, 204, 255));
        roomType.setForeground(new java.awt.Color(102, 102, 102));
        roomType.setText("Enter new room type (STANDARD / PREMIUM / SUITE)");
        roomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeActionPerformed(evt);
            }
        });

        confirm.setBackground(new java.awt.Color(153, 0, 153));
        confirm.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        roomPrice.setBackground(new java.awt.Color(255, 204, 255));
        roomPrice.setForeground(new java.awt.Color(102, 102, 102));
        roomPrice.setText("Enter new price");
        roomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomDetailsPanelLayout = new javax.swing.GroupLayout(roomDetailsPanel);
        roomDetailsPanel.setLayout(roomDetailsPanelLayout);
        roomDetailsPanelLayout.setHorizontalGroup(
            roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                .addGroup(roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(roomDetailsPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(roomDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        roomDetailsPanelLayout.setVerticalGroup(
            roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(roomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomDetailsPrompt)
                .addGap(43, 43, 43)
                .addComponent(hotelID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        getContentPane().add(roomDetailsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotelIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelIDActionPerformed

    private void roomIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomIDActionPerformed

    private void roomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypeActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmActionPerformed

    private void roomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JTextField hotelID;
    private javax.swing.JLabel roomDetails;
    private javax.swing.JPanel roomDetailsPanel;
    private javax.swing.JLabel roomDetailsPrompt;
    private javax.swing.JTextField roomID;
    private javax.swing.JTextField roomPrice;
    private javax.swing.JTextField roomType;
    // End of variables declaration//GEN-END:variables
}
