/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class RoomAvailability extends javax.swing.JFrame {

    /**
     * Creates new form RoomAvailability
     */
    public RoomAvailability() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        roomAvailabilityPanel = new javax.swing.JPanel();
        roomAvailability = new javax.swing.JLabel();
        enterRoomNumber = new javax.swing.JLabel();
        chooseConfirmPrompt = new javax.swing.JLabel();
        confirmBooking = new javax.swing.JButton();
        roomOptionScroll = new javax.swing.JScrollPane();
        roomOptionArea = new javax.swing.JTextArea();
        returnPreviousMenu = new javax.swing.JButton();
        roomNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        roomAvailabilityPanel.setBackground(new java.awt.Color(255, 255, 255));

        roomAvailability.setBackground(new java.awt.Color(255, 255, 255));
        roomAvailability.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        roomAvailability.setForeground(new java.awt.Color(0, 0, 0));
        roomAvailability.setText("Room Availability");
        roomAvailability.setPreferredSize(new java.awt.Dimension(220, 50));

        enterRoomNumber.setBackground(new java.awt.Color(255, 255, 255));
        enterRoomNumber.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        enterRoomNumber.setForeground(new java.awt.Color(0, 0, 0));
        enterRoomNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterRoomNumber.setText("Enter Room Number");

        chooseConfirmPrompt.setBackground(new java.awt.Color(255, 255, 255));
        chooseConfirmPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        chooseConfirmPrompt.setForeground(new java.awt.Color(0, 0, 0));
        chooseConfirmPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseConfirmPrompt.setText("Choose Room & Confirm Booking");

        confirmBooking.setBackground(new java.awt.Color(153, 0, 153));
        confirmBooking.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        confirmBooking.setForeground(new java.awt.Color(255, 255, 255));
        confirmBooking.setText("Confirm Booking");
        confirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingActionPerformed(evt);
            }
        });

        roomOptionArea.setColumns(20);
        roomOptionArea.setRows(5);
        roomOptionArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Rooms", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Helvetica Neue", 1, 13), new java.awt.Color(153, 0, 153))); // NOI18N
        roomOptionScroll.setViewportView(roomOptionArea);

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");
        returnPreviousMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnPreviousMenuActionPerformed(evt);
            }
        });

        roomNumber.setBackground(new java.awt.Color(255, 204, 255));
        roomNumber.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        roomNumber.setForeground(new java.awt.Color(0, 0, 0));
        roomNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        roomNumber.setText("?");
        roomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomAvailabilityPanelLayout = new javax.swing.GroupLayout(roomAvailabilityPanel);
        roomAvailabilityPanel.setLayout(roomAvailabilityPanelLayout);
        roomAvailabilityPanelLayout.setHorizontalGroup(
            roomAvailabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomAvailabilityPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chooseConfirmPrompt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roomAvailabilityPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(roomAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roomAvailabilityPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(roomAvailabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roomAvailabilityPanelLayout.createSequentialGroup()
                        .addComponent(enterRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(roomAvailabilityPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(returnPreviousMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roomAvailabilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomOptionScroll)
                .addContainerGap())
        );
        roomAvailabilityPanelLayout.setVerticalGroup(
            roomAvailabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomAvailabilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseConfirmPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomOptionScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomAvailabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(enterRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnPreviousMenu)
                .addContainerGap())
        );

        getContentPane().add(roomAvailabilityPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmBookingActionPerformed

    private void returnPreviousMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnPreviousMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnPreviousMenuActionPerformed

    private void roomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomAvailability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseConfirmPrompt;
    private javax.swing.JButton confirmBooking;
    private javax.swing.JLabel enterRoomNumber;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton returnPreviousMenu;
    private javax.swing.JLabel roomAvailability;
    private javax.swing.JPanel roomAvailabilityPanel;
    private javax.swing.JTextField roomNumber;
    private javax.swing.JTextArea roomOptionArea;
    private javax.swing.JScrollPane roomOptionScroll;
    // End of variables declaration//GEN-END:variables
}
