/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class RoomManagement extends javax.swing.JFrame {

    /**
     * Creates new form RoomManagementMenu
     */
    public RoomManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomManagementPanel = new javax.swing.JPanel();
        roomManagementMenu = new javax.swing.JLabel();
        chooseOptionPrompt = new javax.swing.JLabel();
        addRoom = new javax.swing.JButton();
        updateRoomDetails = new javax.swing.JButton();
        viewAllRooms = new javax.swing.JButton();
        previousMenu = new javax.swing.JButton();
        removeRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        roomManagementPanel.setBackground(new java.awt.Color(255, 255, 255));

        roomManagementMenu.setBackground(new java.awt.Color(255, 255, 255));
        roomManagementMenu.setFont(new java.awt.Font("STSong", 1, 40)); // NOI18N
        roomManagementMenu.setForeground(new java.awt.Color(0, 0, 0));
        roomManagementMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomManagementMenu.setText("Room Management Menu");
        roomManagementMenu.setPreferredSize(new java.awt.Dimension(220, 50));

        chooseOptionPrompt.setBackground(new java.awt.Color(255, 255, 255));
        chooseOptionPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        chooseOptionPrompt.setForeground(new java.awt.Color(0, 0, 0));
        chooseOptionPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseOptionPrompt.setText("Choose your option");

        addRoom.setBackground(new java.awt.Color(255, 204, 255));
        addRoom.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        addRoom.setForeground(new java.awt.Color(0, 0, 0));
        addRoom.setText("Add Room");

        updateRoomDetails.setBackground(new java.awt.Color(255, 204, 255));
        updateRoomDetails.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        updateRoomDetails.setForeground(new java.awt.Color(0, 0, 0));
        updateRoomDetails.setText("Update Room Details");

        viewAllRooms.setBackground(new java.awt.Color(255, 204, 255));
        viewAllRooms.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        viewAllRooms.setForeground(new java.awt.Color(0, 0, 0));
        viewAllRooms.setText("View All Rooms");

        previousMenu.setBackground(new java.awt.Color(153, 0, 153));
        previousMenu.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        previousMenu.setForeground(new java.awt.Color(255, 255, 255));
        previousMenu.setText("Return to Previous Menu");

        removeRoom.setBackground(new java.awt.Color(255, 204, 255));
        removeRoom.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        removeRoom.setForeground(new java.awt.Color(0, 0, 0));
        removeRoom.setText("Remove Room");

        javax.swing.GroupLayout roomManagementPanelLayout = new javax.swing.GroupLayout(roomManagementPanel);
        roomManagementPanel.setLayout(roomManagementPanelLayout);
        roomManagementPanelLayout.setHorizontalGroup(
            roomManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomManagementPanelLayout.createSequentialGroup()
                .addGroup(roomManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomManagementPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(roomManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(removeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateRoomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAllRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previousMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roomManagementPanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(chooseOptionPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomManagementPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(roomManagementMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        roomManagementPanelLayout.setVerticalGroup(
            roomManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomManagementPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(roomManagementMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(chooseOptionPrompt)
                .addGap(53, 53, 53)
                .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateRoomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewAllRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(previousMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        getContentPane().add(roomManagementPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoom;
    private javax.swing.JLabel chooseOptionPrompt;
    private javax.swing.JButton previousMenu;
    private javax.swing.JButton removeRoom;
    private javax.swing.JLabel roomManagementMenu;
    private javax.swing.JPanel roomManagementPanel;
    private javax.swing.JButton updateRoomDetails;
    private javax.swing.JButton viewAllRooms;
    // End of variables declaration//GEN-END:variables
}
