/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class RoomDetails extends javax.swing.JFrame {

    /**
     * Creates new form RoomDetails
     */
    public RoomDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomDetailsPanel = new javax.swing.JPanel();
        roomDetails = new javax.swing.JLabel();
        roomDetailsPrompt = new javax.swing.JLabel();
        hotelID = new javax.swing.JTextField();
        roomID = new javax.swing.JTextField();
        confirmUpdate = new javax.swing.JButton();
        roomPrice = new javax.swing.JTextField();
        returnPreviousMenu = new javax.swing.JButton();
        chooseRoomType = new javax.swing.JLabel();
        roomType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        roomDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        roomDetails.setBackground(new java.awt.Color(255, 255, 255));
        roomDetails.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        roomDetails.setForeground(new java.awt.Color(0, 0, 0));
        roomDetails.setText("Room Details");
        roomDetails.setPreferredSize(new java.awt.Dimension(220, 50));

        roomDetailsPrompt.setBackground(new java.awt.Color(255, 255, 255));
        roomDetailsPrompt.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        roomDetailsPrompt.setForeground(new java.awt.Color(0, 0, 0));
        roomDetailsPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomDetailsPrompt.setText("Enter Room Details");

        hotelID.setBackground(new java.awt.Color(255, 204, 255));
        hotelID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        hotelID.setForeground(new java.awt.Color(102, 102, 102));
        hotelID.setText("Enter hotel ID");

        roomID.setBackground(new java.awt.Color(255, 204, 255));
        roomID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        roomID.setForeground(new java.awt.Color(102, 102, 102));
        roomID.setText("Enter room ID to update");

        confirmUpdate.setBackground(new java.awt.Color(153, 0, 153));
        confirmUpdate.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        confirmUpdate.setForeground(new java.awt.Color(255, 255, 255));
        confirmUpdate.setText("Confirm Update");

        roomPrice.setBackground(new java.awt.Color(255, 204, 255));
        roomPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        roomPrice.setForeground(new java.awt.Color(102, 102, 102));
        roomPrice.setText("Enter new price");

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");

        chooseRoomType.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        chooseRoomType.setForeground(new java.awt.Color(102, 102, 102));
        chooseRoomType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseRoomType.setText("Choose Room Type");

        roomType.setBackground(new java.awt.Color(255, 204, 255));
        roomType.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        roomType.setForeground(new java.awt.Color(0, 0, 0));
        roomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STANDARD", "PREMIUM", "SUITE" }));
        roomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomDetailsPanelLayout = new javax.swing.GroupLayout(roomDetailsPanel);
        roomDetailsPanel.setLayout(roomDetailsPanelLayout);
        roomDetailsPanelLayout.setHorizontalGroup(
            roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                .addGroup(roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(roomDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomDetailsPanelLayout.createSequentialGroup()
                                .addComponent(chooseRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(roomDetailsPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(returnPreviousMenu)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        roomDetailsPanelLayout.setVerticalGroup(
            roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomDetailsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(roomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomDetailsPrompt)
                .addGap(29, 29, 29)
                .addComponent(hotelID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(roomDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(roomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnPreviousMenu)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(roomDetailsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseRoomType;
    private javax.swing.JButton confirmUpdate;
    private javax.swing.JTextField hotelID;
    private javax.swing.JButton returnPreviousMenu;
    private javax.swing.JLabel roomDetails;
    private javax.swing.JPanel roomDetailsPanel;
    private javax.swing.JLabel roomDetailsPrompt;
    private javax.swing.JTextField roomID;
    private javax.swing.JTextField roomPrice;
    private javax.swing.JComboBox<String> roomType;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getConfirm() {
        return confirmUpdate;
    }

    public javax.swing.JTextField getHotelID() {
        return hotelID;
    }

    public javax.swing.JButton getReturnPreviousMenu() {
        return returnPreviousMenu;
    }

    public javax.swing.JTextField getRoomID() {
        return roomID;
    }

    public javax.swing.JTextField getRoomPrice() {
        return roomPrice;
    }

    public String getRoomType() {
        return (String) roomType.getSelectedItem();
    }
}
