/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignIn = new javax.swing.JPanel();
        LoginWelcome = new javax.swing.JLabel();
        CredentialsMessage = new javax.swing.JLabel();
        LoginUserName = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        SignUpOptionPrompt = new javax.swing.JLabel();
        SignUpOption = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        SignIn.setBackground(new java.awt.Color(255, 255, 255));

        LoginWelcome.setBackground(new java.awt.Color(255, 255, 255));
        LoginWelcome.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        LoginWelcome.setForeground(new java.awt.Color(0, 0, 0));
        LoginWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginWelcome.setText("Welcome Back");
        LoginWelcome.setToolTipText("");

        CredentialsMessage.setBackground(new java.awt.Color(255, 255, 255));
        CredentialsMessage.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        CredentialsMessage.setForeground(new java.awt.Color(0, 0, 0));
        CredentialsMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CredentialsMessage.setText("Enter your credentials to login");

        LoginUserName.setBackground(new java.awt.Color(255, 204, 255));
        LoginUserName.setForeground(new java.awt.Color(102, 102, 102));
        LoginUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LoginUserName.setText("User Name");
        LoginUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUserNameActionPerformed(evt);
            }
        });

        LoginPassword.setBackground(new java.awt.Color(255, 204, 255));
        LoginPassword.setForeground(new java.awt.Color(102, 102, 102));
        LoginPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LoginPassword.setText("Password");
        LoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPasswordActionPerformed(evt);
            }
        });

        Login.setBackground(new java.awt.Color(255, 51, 255));
        Login.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");

        SignUpOptionPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpOptionPrompt.setText("Don't have an account?");

        SignUpOption.setBackground(new java.awt.Color(255, 255, 255));
        SignUpOption.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        SignUpOption.setForeground(new java.awt.Color(204, 0, 204));
        SignUpOption.setText("Sign Up");

        javax.swing.GroupLayout SignInLayout = new javax.swing.GroupLayout(SignIn);
        SignIn.setLayout(SignInLayout);
        SignInLayout.setHorizontalGroup(
            SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CredentialsMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SignInLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginPassword)
                            .addComponent(LoginUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(SignInLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(SignUpOptionPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUpOption, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        SignInLayout.setVerticalGroup(
            SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LoginWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CredentialsMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(LoginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpOptionPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUpOption, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        getContentPane().add(SignIn, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUserNameActionPerformed

    private void LoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CredentialsMessage;
    private javax.swing.JButton Login;
    private javax.swing.JTextField LoginPassword;
    private javax.swing.JTextField LoginUserName;
    private javax.swing.JLabel LoginWelcome;
    private javax.swing.JPanel SignIn;
    private javax.swing.JButton SignUpOption;
    private javax.swing.JLabel SignUpOptionPrompt;
    // End of variables declaration//GEN-END:variables
}
