/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author alex
 */
public class ViewBookingGuest extends javax.swing.JFrame {

    /**
     * Creates new form DisplayBooking
     */
    public ViewBookingGuest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayBookingPanel = new javax.swing.JPanel();
        bookings = new javax.swing.JLabel();
        scrollBookingsPanel = new javax.swing.JScrollPane();
        bookingViewArea = new javax.swing.JTextArea();
        returnPreviousMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        displayBookingPanel.setBackground(new java.awt.Color(255, 204, 255));

        bookings.setBackground(new java.awt.Color(255, 204, 255));
        bookings.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        bookings.setForeground(new java.awt.Color(0, 0, 0));
        bookings.setText("Bookings");
        bookings.setPreferredSize(new java.awt.Dimension(220, 50));

        bookingViewArea.setColumns(20);
        bookingViewArea.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bookingViewArea.setRows(5);
        bookingViewArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "booking view", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Helvetica Neue", 1, 13), new java.awt.Color(153, 0, 153))); // NOI18N
        scrollBookingsPanel.setViewportView(bookingViewArea);

        returnPreviousMenu.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        returnPreviousMenu.setForeground(new java.awt.Color(153, 0, 153));
        returnPreviousMenu.setText("Return");

        javax.swing.GroupLayout displayBookingPanelLayout = new javax.swing.GroupLayout(displayBookingPanel);
        displayBookingPanel.setLayout(displayBookingPanelLayout);
        displayBookingPanelLayout.setHorizontalGroup(
            displayBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollBookingsPanel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(displayBookingPanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(bookings, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayBookingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnPreviousMenu)
                .addGap(255, 255, 255))
        );
        displayBookingPanelLayout.setVerticalGroup(
            displayBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayBookingPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bookings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollBookingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnPreviousMenu)
                .addGap(12, 12, 12))
        );

        getContentPane().add(displayBookingPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBookingGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBookingGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBookingGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBookingGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBookingGuest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bookingViewArea;
    private javax.swing.JLabel bookings;
    private javax.swing.JPanel displayBookingPanel;
    private javax.swing.JButton returnPreviousMenu;
    private javax.swing.JScrollPane scrollBookingsPanel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getReturnPreviousMenu() {
        return returnPreviousMenu;
    }
    
    public javax.swing.JTextArea getBookingViewArea() {
        return bookingViewArea;
    }

}
